# loading Libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# loading Datasets

In [2]:
Dim_Customers = pd.read_csv("D:\mohanad study\ERU Study\level 3\semester 2\Predictive Analytics\project\GoldExports\Gold_Dim_Customers_2026-05-08.csv")
Dim_Date = pd.read_csv("D:\mohanad study\ERU Study\level 3\semester 2\Predictive Analytics\project\GoldExports\Gold_Dim_Date_2026-05-08.csv")
Dim_Products = pd.read_csv("D:\mohanad study\ERU Study\level 3\semester 2\Predictive Analytics\project\GoldExports\Gold_Dim_Products_2026-05-08.csv")
Dim_Sellers = pd.read_csv("D:\mohanad study\ERU Study\level 3\semester 2\Predictive Analytics\project\GoldExports\Gold_Dim_Sellers_2026-05-08.csv")
Fact_Orders = pd.read_csv("D:\mohanad study\ERU Study\level 3\semester 2\Predictive Analytics\project\GoldExports\Gold_Fact_Orders_2026-05-08.csv")
Fact_Orders_Items = pd.read_csv("D:\mohanad study\ERU Study\level 3\semester 2\Predictive Analytics\project\GoldExports\Gold_Fact_Order_Items_2026-05-08.csv")
Fact_Marketing = pd.read_csv("D:\mohanad study\ERU Study\level 3\semester 2\Predictive Analytics\project\GoldExports\Gold_Fact_Marketing_Funnel_2026-05-08.csv")

In [3]:
Dim_Customers.head()

,customer_unique_id,zip_code,city,state,latitude,longitude,load_date_timestamp
0,0000366f3b9a7992bf8c76cfdf3221e2,7787,cajamar,SP,-23.340235,-46.830140,5/7/2026 11:19:13 PM
1,0000b849f77a49e4a4ce2b2a4ca5be3f,6053,osasco,SP,-23.559115,-46.787626,5/7/2026 11:19:13 PM
2,0000f46a3911fa3c0805444483337064,88115,sao jose,SC,-27.542880,-48.633426,5/7/2026 11:19:13 PM
3,0000f6ccb0745a6a4b88665a16c9f078,66812,belem,PA,-1.312214,-48.483159,5/7/2026 11:19:13 PM
4,0004aac84e0df4da2b147fca70cf8255,18040,sorocaba,SP,-23.505548,-47.469705,5/7/2026 11:19:13 PM

In [4]:
Dim_Date.head()

,date_key,full_date,year_number,quarter_number,month_number,month_name,day_name,is_weekend,load_date_timestamp
0,20150101,1/1/2015 12:00:00 AM,2015,1,1,January,Thursday,False,5/7/2026 11:19:11 PM
1,20150102,1/2/2015 12:00:00 AM,2015,1,1,January,Friday,False,5/7/2026 11:19:11 PM
2,20150103,1/3/2015 12:00:00 AM,2015,1,1,January,Saturday,True,5/7/2026 11:19:11 PM
3,20150104,1/4/2015 12:00:00 AM,2015,1,1,January,Sunday,True,5/7/2026 11:19:11 PM
4,20150105,1/5/2015 12:00:00 AM,2015,1,1,January,Monday,False,5/7/2026 11:19:11 PM

In [5]:
Dim_Products.head()

,product_id,category_name_pt,category_name_en,name_length,description_length,photo_count,weight_g,length_cm,height_cm,width_cm,volume_cm3,load_date_timestamp
0,00066f42aeeb9f3007548bb9d3f33c38,perfumaria,perfumery,53.0,596.0,6.0,300.0,20.0,16.0,16.0,5120.0,5/7/2026 11:19:11 PM
1,00088930e925c41fd95ebfe695fd2655,automotivo,auto,56.0,752.0,4.0,1225.0,55.0,10.0,26.0,14300.0,5/7/2026 11:19:11 PM
2,0009406fd7479715e4bef61dd91f2462,cama mesa banho,bed bath table,50.0,266.0,2.0,300.0,45.0,15.0,35.0,23625.0,5/7/2026 11:19:11 PM
3,000b8f95fcb9e0096488278317764d19,utilidades domesticas,housewares,25.0,364.0,3.0,550.0,19.0,24.0,12.0,5472.0,5/7/2026 11:19:11 PM
4,000d9be29b5207b54e86aa1b1ac54872,relogios presentes,watches gifts,48.0,613.0,4.0,250.0,22.0,11.0,15.0,3630.0,5/7/2026 11:19:11 PM

In [6]:
Dim_Sellers.head()

,seller_id,zip_code,city,state,latitude,longitude,business_segment,business_type,lead_type,behaviour_profile,catalog_size,declared_monthly_revenue,came_from_marketing,load_date_timestamp
0,0015a82c2db000af6aaaf3ae2ecb0532,9080,santo andre,SP,-23.640444,-46.541742,NaN,NaN,NaN,NaN,NaN,NaN,False,5/7/2026 11:19:16 PM
1,001cca7ae9ae17fb1caed9dfb1094831,29156,cariacica,ES,-20.278513,-40.411675,NaN,NaN,NaN,NaN,NaN,NaN,False,5/7/2026 11:19:16 PM
2,001e6ad469a905060d959994f1b41e4f,24754,sao goncalo,RJ,-22.872355,-43.027433,NaN,NaN,NaN,NaN,NaN,NaN,False,5/7/2026 11:19:16 PM
3,002100f778ceb8431b7a1020ff7ab48f,14405,franca,SP,-20.528759,-47.411110,NaN,NaN,NaN,NaN,NaN,NaN,False,5/7/2026 11:19:16 PM
4,003554e2dce176b5555353e4f3555ac8,74565,goiania,GO,-16.640574,-49.276483,NaN,NaN,NaN,NaN,NaN,NaN,False,5/7/2026 11:19:16 PM

In [7]:
Fact_Orders.head()

,order_id,customer_unique_id,purchase_date_key,order_status,total_payment,primary_payment_type,review_score,review_text,delivery_days_actual,is_late_delivery,is_invalid_payment,load_date_timestamp
0,00010242fe8c5a6d1ba2dd792cb16214,871766c5855e863f6eccc05f988b23cb,20170913,delivered,72.19,credit card,5.0,perfeito produto entregue antes do combinado,7.0,False,False,5/7/2026 11:19:17 PM
1,00018f77f2f0320c557190d7a144bdd3,eb28e67c4c0b83846050ddfb8a35d051,20170426,delivered,259.83,credit card,4.0,NaN,16.0,False,False,5/7/2026 11:19:17 PM
2,000229ec398224ef6ca0657da4fc703e,3818d81c6709e39d06b2738a8d3a2474,20180114,delivered,216.87,credit card,5.0,chegou antes do prazo previsto e o produto sur...,8.0,False,False,5/7/2026 11:19:17 PM
3,00024acbcdf0a6daa1e931b038114c75,af861d436cfc08b2c2ddefd0ba074622,20180808,delivered,25.78,credit card,4.0,NaN,6.0,False,False,5/7/2026 11:19:17 PM
4,00042b26cf59d7ce69dfabb4e55b4fd9,64b576fb70d441e8f1b2d7d446e483c5,20170204,delivered,218.04,credit card,5.0,gostei pois veio no prazo determinado,25.0,False,False,5/7/2026 11:19:17 PM

In [8]:
Fact_Orders_Items.head()

,order_item_key,order_id,product_id,seller_id,purchase_date_key,order_purchase_timestamp,order_delivered_customer_date,price,freight_value,total_item_value,load_date_timestamp
0,1,00010242fe8c5a6d1ba2dd792cb16214,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,20170913,9/13/2017 8:59:00 AM,9/20/2017 11:43:00 PM,58.90,13.29,72.19,5/7/2026 11:19:25 PM
1,2,00018f77f2f0320c557190d7a144bdd3,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,20170426,4/26/2017 10:53:00 AM,5/12/2017 4:04:00 PM,239.90,19.93,259.83,5/7/2026 11:19:25 PM
2,3,000229ec398224ef6ca0657da4fc703e,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,20180114,1/14/2018 2:33:00 PM,1/22/2018 1:19:00 PM,199.00,17.87,216.87,5/7/2026 11:19:25 PM
3,4,00024acbcdf0a6daa1e931b038114c75,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,20180808,8/8/2018 10:00:00 AM,8/14/2018 1:32:00 PM,12.99,12.79,25.78,5/7/2026 11:19:25 PM
4,5,00042b26cf59d7ce69dfabb4e55b4fd9,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,20170204,2/4/2017 1:57:00 PM,3/1/2017 4:42:00 PM,199.90,18.14,218.04,5/7/2026 11:19:25 PM

In [9]:
Fact_Marketing.head()

,mql_id,seller_id,first_contact_date_key,won_date_key,lead_origin,landing_page_id,sdr_id,sr_id,is_converted,days_to_close,load_date_timestamp
0,0002ac0d783338cfeab0b2bdbd872cda,NaN,20171114,NaN,unknown,b76ef37428e6799c421989521c0e5077,NaN,NaN,False,NaN,5/7/2026 11:19:29 PM
1,000dd3543ac84d906eae52e7c779bb2a,NaN,20180405,20180424.0,organic search,b48ec5f3b04e9068441002a19df93c6c,a8387c01a09e99ce014107505b92388c,9e4d1098a3b0f5da39b0bc48f9876645,True,19.0,5/7/2026 11:19:29 PM
2,001d3439223b7bb23ed89b9c8890d096,NaN,20180414,NaN,paid search,35c9b150ab36fe584c1f24fd458c453a,NaN,NaN,False,NaN,5/7/2026 11:19:29 PM
3,00275937100699204a3d5ae3caf7190d,NaN,20180111,NaN,organic search,a7982125ff7aa3b2054c6e44f9d28522,NaN,NaN,False,NaN,5/7/2026 11:19:29 PM
4,003d859bbd84a526b9e06340ce7d185f,NaN,20180402,NaN,direct traffic,22c29808c4f815213303f8933030604c,NaN,NaN,False,NaN,5/7/2026 11:19:29 PM